import Head from "next/head";
import React, {FC, ReactNode, useCallback, useState} from "react"

interface IDefault {
  children: ReactNode,
  title: string,
}

const BodyLayout = React.createContext<{bodyClick: (cb: () => void) => void }>(null);

const Default: FC<IDefault> = ({children, title}) => {
  const [date, setDate] = useState<number>(Date.now());
  const reload = useCallback((cb) => {
    console.log('cb BodyLayout')
    cb()
  }, [date]);

  const bodyClick = (e: React.MouseEvent<HTMLDivElement>) => {
    console.log('bodyClick')
    setDate(Date.now())
  }

  return (
    <>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:title" content={`My page ${title}`} key="title" />
      <link rel="icon" href="/login32x44.ico" />
    </Head>
      <BodyLayout.Provider value={{bodyClick: reload}}>
        <div onClick={bodyClick} className="">{children}</div>
      </BodyLayout.Provider>
    </>);
}

export { BodyLayout };
export default Default;