import Head from "next/head";
import React, { FC, ReactNode } from "react"

interface IDefault {
  children: ReactNode,
  title: string,
}

const Default: FC<IDefault> = ({children, title}) => {
  return (
    <>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:title" content={`My page ${title}`} key="title" />
      <link rel="icon" href="/login32x44.ico" />
    </Head>
    <div className="">{children}</div>
    </>);
}

export default Default