name: github-actions
run-name: GitHub Actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g bats
      - run: bats -v
      - name: build
        working-directory: /app
        run: npm run build



